name: Sprite Commit
run-name: 👾 ${{ github.actor }} is making a commit 🛸
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: >
        -Darcadedb.server.rootPassword=playwithdata
        -Darcadedb.dumpConfigAtStartup=true
        -Darcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}
    services:
      arcade:
        image: arcadedata/arcadedb:latest
        ports:
          - 2480:2480 # host : container port
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Run unit tests
        run: npm test:unit

      # - name: Run integration tests
      #   run: npm test:integration

      - run: echo "🍏 This job's status is ${{ job.status }}."


name: CI
on: [push]
jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      arcadeDB:
        image: arcadeDB/arcadeDB:latest
        ports:
          - 2480:2480
        options: --health-cmd="curl http://localhost:2480" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up database
      run: |
        curl -X POST http://localhost:2424/command/arcadedb/sql -d 'create database mydb'
        curl -X POST http://localhost:2424/command/mydb/sql -d '@/path/to/brewery_dataset.sql'

    - name: Run tests
      run: |
        pytest tests/integration_tests/

    - name: Teardown database
      run: |
        curl -X POST http://localhost:2424/command/arcadedb/sql -d 'drop database mydb'
